### ISSUE TITLE
zsh.com does not automatically run ape executables on M1 Mac

### ISSUE THREAD

**Issue by mrdomino** [ahgamut/superconfigure#15]
```console
% make o/aarch64/examples/hello.com
% o/aarch64/examples/hello.com
zsh: exec format error: o/aarch64/examples/hello.com
% ape o/aarch64/examples/hello.com
hello world
```

Was anything special done to bash.com to make it support this? If so then the same thing needs done to zsh.com. If not then we should figure out why zsh talks funny and fix it.

**Comment by jart** [comment]
Do you have `ape` installed to `/usr/local/bin/ape`?

**Comment by mrdomino** [comment]
It's not happening on the current version of zsh, so I'm going to close this as completed.
