### ISSUE TITLE
Blink instead of Qemu?

### ISSUE THREAD

**Issue by workspace-public** [ahgamut/superconfigure#20]
As it says on the tin, can we have blink from cosmo instead of Qemu?

**Comment by jart** [comment]
As happy as I am to see you making this suggestion, Qemu is probably a better fit for superconfigure right now. Blink is great for testing and visualization when you know that it supports all the system calls you need. However Qemu still has greater coverage for Linux users, and better binfmt_misc integration. I hope Blink can fully replace Qemu for our needs one day soon though!
