### ISSUE TITLE
Request: Windows installer like Cygwin

### ISSUE THREAD

**Issue by fithisux** [ahgamut/superconfigure#53]
Wishful thinking!

**Comment by ahgamut** [comment]
Installer for what? Just download the zip files, extract, rename to `.exe` and run the executable

**Comment by fithisux** [comment]
It does not work @ahgamut , the corporate antivirus software marks them as threats and starts deleting them immediately.

In any case, at some point there can be something like cygwin to update what is new.

Tremendous work by the way! Thank you for the effort.

**Comment by ahgamut** [comment]
Oh, don't think I can do anything about AV checks from here -- there was a similar issue https://github.com/jart/cosmopolitan/issues/342 a while back.

Happy you like the project though! Maybe once the builds are better tested/checked we can try to have an installer or something.
