### ISSUE TITLE
Blog Doesn't have Comments

### ISSUE THREAD

**Issue by jeff-hykin** [ahgamut/superconfigure#7]
I can't say thank you on your blog so I'm going to here! This is one of the most important projects in the entirety of software development. And all the people who indirectly use/depend on this will probably have no idea so consider this a thank you from them as well.

I've just got one thing to ask. When you say the exectuable even runs on windows, you're saying I can put one of those binaries on a flash drive, plug it into a linux machine, do a `./tree.exe` see the output, then plug the usb drive into a windows 10 machine, do a .\tree.exe and also see the output??

**Comment by ahgamut** [comment]
Yes, I think if it was named `tree.exe` or `tree.com` (`.com` is what Cosmpolitan Libc originally used), it should work. I haven't tried it myself on a Windows system because I don't have a Windows system right now, so if it does work, please post a screenshot here.

> you're saying I can put one of those binaries on a flash drive, plug it into a linux machine, do a ./tree.exe see the output, then plug the usb drive into a windows 10 machine, do a .\tree.exe and also see the output??

yes, this was one of the reasons why I put this repo together :)

**Comment by jeff-hykin** [comment]
> I haven't tried it myself on a Windows system because I don't have a Windows system right now

Actually I'm asking because I refuse to run windows but I want some of my stuff to be cross platform 😆. I'll eventually have some students test it though and lots of them have windows.

This means my gullotine library isnt the first universal executable, just the first interpreted universal executable.

I'm super excited to finally have a universal git binary. This opens up a ton of doors for bootstrapping scripts that need to pull down repos.

**Comment by ahgamut** [comment]
Nice to hear! Still testing out all the uses of the APE `git` binary.
Let mw know what other executables you'd like to see in this collection!

**Comment by jart** [comment]
> Actually I'm asking because I refuse to run windows but I want some of my stuff to be cross platform 😆. I'll eventually have some students test it though and lots of them have windows.

That would make you our intended audience. If you stick to the standard POSIX interfaces (e.g. unistd, stdio, sockets, etc.) when developing your programs on Linux, then it may likely be the case that release binaries you distribute will work on Windows the first time.

**Comment by jeff-hykin** [comment]
Great 👍
