### ISSUE TITLE
[Request] Splitting packages

### ISSUE THREAD

**Issue by vazub** [ahgamut/superconfigure#8]
It would be awesome if the provided release archives were split per package, so that each can be downloaded individually. If nothing else, at least getting Git and Lua separated would be much appreciated.

**Comment by ahgamut** [comment]
But `lua` is in `cli.zip` and `git` is in `web.zip`. Do you mean you'd like to have each executable available individually?

**Comment by vazub** [comment]
Yes, exactly that. For example, I might want to download Lua only, without taking the whole 40 MB cli.zip of otherwise unneeded programs.

**Comment by ahgamut** [comment]
Hmm each executable individually might be too many. I was thinking of having something like `lang.zip` which only has `lua`, `quickjs`, `berry`, and similarly "small" language runtimes in a future release.

**Comment by vazub** [comment]
How many packages do you plan to provide in future? Will the list grow? If this is all there is, splitting just some of those, like Git and Lua should suffice, I think. But if you plan to have a big registry of APE tools pre-built, it would probably make sense to start splitting them right away, so that they can be downloaded separately, on a per-need basis. Or at least considering to have a rule of thumb - if a single tool is over 10 MB, it should be separate?

**Comment by jart** [comment]
Hi everyone. You can now download the latest individual build artifacts at https://cosmo.zip/pub/cosmos/latest/ Thanks go out to @ingenieroariel who donated the domain name.

**Comment by jart** [comment]
I've renamed the URL to https://cosmo.zip/pub/cosmos/MODE=/

**Comment by vazub** [comment]
Ah, awesome, thanks @jart! Exactly what I was looking for! :+1: 
May I kindly ask to add Git to /bin as well? Seems to be missing atm.

**Comment by ahgamut** [comment]
Git I have added as a zip file https://cosmo.zip/pub/cosmos/zip/git.zip because git needs that specific folder structure to work properly.
